In [1]:

import numpy as np
import pandas as pd
from pymatgen.core.operations import SymmOp
from pymatgen.ext.matproj import MPRester
from jupyter_jsmol.pymatgen import quick_view
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from pymatgen.core import Lattice, Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.io.cif import CifWriter
import tempfile

In [2]:
mp_key = "jkj1S0TLmQtlvQmGDoUQvq5XQzLfKlCF"
mp_id = "mp-14437"

In [3]:
#je reprend mes valeurs du dernier devoir
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:

spaceAnalyzer = SpacegroupAnalyzer(prim_struc)
data2 = spaceAnalyzer.get_conventional_standard_structure()
symopc= SpacegroupAnalyzer(data2).get_symmetry_operations()
inversion = symopc[1]
rotation = symopc[7]
translation = symopc[12]
print(inversion.as_xyz_str())
print(rotation.as_xyz_str())
print(translation.as_xyz_str())
print(inversion)
print(rotation)
print(translation)

#


-x, -y, -z
-y, -x, z
x+2/3, y+1/3, z+1/3
Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.66666667 0.33333333 0.33333333]


In [5]:
view = quick_view(data2,"packed", conventional=True)
display(view)
RB= data2.sites[0].frac_coords
Y = data2.sites[3].frac_coords
O = data2.sites[6].frac_coords
O2= data2.sites[9].frac_coords
print("\n coordonnées de l'atome RB :")
print(RB)
print("\n coordonnées de l'atome Y  :")
print(Y)
print("\n coordonnées de l'atome O  :")
print(O)
print("\n coordonnées de l'atome O2  :")
print(O2)

JsmolView(layout=Layout(align_self='stretch', height='400px'))


 coordonnées de l'atome RB :
[0. 0. 0.]

 coordonnées de l'atome Y  :
[0.33333333 0.66666667 0.16666667]

 coordonnées de l'atome O  :
[0.66666667 0.33333333 0.1080395 ]

 coordonnées de l'atome O2  :
[0.66666667 0.33333333 0.55862716]


In [13]:
print("Je calcule les valeurs des positions après transformation\n")
IOUT = inversion.operate_multi(O2)
print(IOUT)
print("\n")
RTOUT= rotation.operate_multi(Y)
print(RTOUT)
print("\n")
TOUT = translation.operate_multi(RB)
print(TOUT)


Je calcule les valeurs des positions après transformation

[-0.66666667 -0.33333333 -0.55862716]


[-0.66666667 -0.33333333  0.16666667]


[0.66666667 0.33333333 0.33333333]


In [8]:
view_invers = quick_view(data2)
display(view_invers)
view_invers.script("draw symop 2 {atomno=10}") 

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [9]:
view_rotation = quick_view(data2)
display(view_rotation)
view_rotation.script("draw symop 8 {atomno=4}") 

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [10]:
view_translation = quick_view(data2)
display(view_translation)
view_translation.script("draw symop 13 {atomno=1}") 

JsmolView(layout=Layout(align_self='stretch', height='400px'))